[project]
authors = ["Chaberis <chaberwork@mail.ru>"]
channels = ["conda-forge"]
name = "project_territory_planning"
platforms = ["win-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
geopandas = ">=1.0.1,<2"
shapely = ">=2.0.7,<3"
matplotlib = ">=3.10.1,<4"
jupyter = ">=1.1.1,<2"
plotly = ">=6.0.0,<7"
numpy = ">=2.2.3,<3"
